# **Assignmment 1 - ENEL 645 - Group 3**

### **1. Import the numpy package under the name np**

In [63]:
import numpy as np

### **2. Print the numpy version and the configuration**

In [64]:
print('Numpy version is: ',np.version.version)
print('\n')
print('Below is the Numpy configuration\n\n')
np.show_config()

Numpy version is:  1.21.2


Below is the Numpy configuration


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this Num

### **3. Create a 1D array of zeros of size 10 of type float32**

In [65]:
zero_array = np.zeros(10, dtype='float32')
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### **4. Print the memory size of the array below**

In [66]:
Z = np.zeros((32,12))
# Include your solution below

print(f'The memory size of the array above in bytes is: {Z.nbytes} bytes')

The memory size of the array above in bytes is: 3072 bytes


### **5. Create a 1D array with values ranging from 10 to 58**

In [67]:
array = np.arange(10,59) # considering 58 to be inclusive in the array.
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


### **6. Reverse the order of the values in the vector (first element becomes last)**

In [68]:
array = np.arange(10)
# Include your solution below

reversed_array = array[::-1]
print('base vector:\n ',array,'\n')
print('reversed:\n', reversed_array)

base vector:
  [0 1 2 3 4 5 6 7 8 9] 

reversed:
 [9 8 7 6 5 4 3 2 1 0]


### **7. Create a 3x3 matrix with values ranging from 0 to 8**

In [69]:
matrix = np.arange(9).reshape(3,3) # first created a 1D array and then reshape it to a 3x3 array
print('A 3x3 matrix with values ranging from 0 to 8 is shown below\n\n',matrix)

A 3x3 matrix with values ranging from 0 to 8 is shown below

 [[0 1 2]
 [3 4 5]
 [6 7 8]]


### **8. Create a 3x3 identity matrix**

In [70]:
id_matrix = np.identity(3)
print('below is a 3x3 identity Matrix\n\n',id_matrix)

below is a 3x3 identity Matrix

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### **9. Find and print the maximum values of each column in the array below**

In [71]:
Z = np.random.random((10,11))
# Include your solution below

# order z so highest values are on last row
Z.sort(axis=0)
# create array with last row
highest_values_array = Z[-1,:]
# for each value in array, print column number and value
for i in range(0,highest_values_array.shape[0]):
    print(f"highest value column {i}: {highest_values_array[i]}")

highest value column 0: 0.9447877718147288
highest value column 1: 0.9046507589664651
highest value column 2: 0.9686129955426129
highest value column 3: 0.910125443521187
highest value column 4: 0.7164023865164916
highest value column 5: 0.9121777973310791
highest value column 6: 0.8816770885967635
highest value column 7: 0.9907157594530274
highest value column 8: 0.9701546777864137
highest value column 9: 0.9477099048396386
highest value column 10: 0.7779500838016237


### **10. Create a 7x7 array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [72]:
matrix = np.zeros((5,5))
print(np.pad(matrix,(1,1),'constant',constant_values=(1,1)))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### **11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [73]:
Z = np.ones((5,5))
# Include your solution below
print("Original Array:")
print(Z)

#using pad function to pad matrix with zeros
padded_array = np.pad(Z,(1,1),'constant',constant_values = (0,0))
print("Padded with zeros using pad function:")
print(padded_array)

Original Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Padded with zeros using pad function:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### **12. Extract the integer part of the random array of positive numbers below**

In [74]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print("Random array:")
print(Z)

int_array = np.array(Z, int) #Getting the integer part of the array elements
print("Extracting the integer parts of the random array:")
print(int_array)

Random array:
[0.35399904 3.69861398 7.92720263 6.64669358 4.04851434 4.75490834
 4.08123214 4.1743191  4.94892113 9.62724872]
Extracting the integer parts of the random array:
[0 3 7 6 4 4 4 4 4 9]


### **13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

In [75]:
base_array = np.arange(5)

matrix = np.tile(base_array,(5,1)) #using tile function to create a 5x5 matrix rows equal to the base array
print("5x5 matrix with rows [0,1,2,3,4]:")
print(matrix)

5x5 matrix with rows [0,1,2,3,4]:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### **14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

In [76]:
vector = np.linspace(0, 1, num = 11, endpoint = False)[1:]
print("vector = ", vector) #Size 10 Vector with values in between 0 an 1

vector =  [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### **15. Create a random vector of size 10 and sort it**

In [77]:
Z = np.random.random(10) #initializing random vector of size 10
print("Unsorted random vector:")
print("\nZ = ", Z)
Z.sort()
print("\nSorted random Vector:")
print("\nZ = ", Z)

Unsorted random vector:

Z =  [0.93244092 0.33788226 0.45592203 0.0394687  0.26847817 0.80445185
 0.9264587  0.1725485  0.91170053 0.46107559]

Sorted random Vector:

Z =  [0.0394687  0.1725485  0.26847817 0.33788226 0.45592203 0.46107559
 0.80445185 0.91170053 0.9264587  0.93244092]


### **16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [78]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below

R = np.sqrt(X**2 + Y**2) #Hypotenuse
T = np.arctan((Y/X)) #Angle in radians
print("Below are the cartesian coordinates:\n X = ",X,"\n Y = ",Y)
print("\nBelow are the Polar coordinates:\n R = ",R,"\n T = ",T)

Below are the cartesian coordinates:
 X =  [0.22236171 0.66775646 0.50140448 0.25889818 0.66161792 0.85269077
 0.3670706  0.27233802 0.29649191 0.5231975 ] 
 Y =  [0.49986723 0.76520021 0.17806758 0.29264968 0.93561035 0.05557753
 0.71481519 0.1449058  0.92092824 0.16058213]

Below are the Polar coordinates:
 R =  [0.54709412 1.01559345 0.53208506 0.39073277 1.14590794 0.85450009
 0.80355558 0.30848936 0.96747935 0.54728626] 
 T =  [1.15224045 0.85329552 0.34124439 0.8465161  0.95528705 0.06508694
 1.09639275 0.48898158 1.25932644 0.29779737]


### **17. Create random vector of size 10 and replace the maximum value by 0**

In [79]:
Z = np.random.random(10) #Initializing random vector of size 10
print("Random vector:\n Z = ", Z)

Z[Z.argmax()] = 0
print("Replacing the maximum value with zero:\n Z = ", Z)

Random vector:
 Z =  [0.90629326 0.84483098 0.74270139 0.81218521 0.84961121 0.17333633
 0.97122664 0.63534637 0.82633795 0.21897281]
Replacing the maximum value with zero:
 Z =  [0.90629326 0.84483098 0.74270139 0.81218521 0.84961121 0.17333633
 0.         0.63534637 0.82633795 0.21897281]


### **18. Find the nearest value from a given value (z) in an array (Z)**

In [80]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

print("Random Array Z = ", Z)
#get index of mininum value of array of absolute values of Z-z
closest_value_index = (np.abs(Z-z)).argmin()
closest_value = Z[closest_value_index]
print("Closest element in the array Z to z=0.5 = ", closest_value)

Random Array Z =  [0.79673418 0.97309873 0.26784188 0.02779003 0.8783285  0.25447397
 0.38661796 0.69515325 0.61669996 0.1936924 ]
Closest element in the array Z to z=0.5 =  0.386617955564996


### **19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [81]:
Z = np.arange(1,6)[::-1]
# Include your solution below

print("Original Array:")
print(Z)

n_zeros = 3 #number of zeros to interleave
print("Array length = ", (len(Z))) #Check length of the array
print("Interleave length = ", (len(Z)-1)*(n_zeros)) #Checking intervals *p (3 zero intervals)
new_Z = np.zeros(len(Z) + (len(Z)-1)*(n_zeros))
new_Z[::n_zeros+1] = Z
print("\nNew array:")
print(new_Z)

Original Array:
[5 4 3 2 1]
Array length =  5
Interleave length =  12

New array:
[5. 0. 0. 0. 4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1.]


### **20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0) x (5,5), (5,5,1) x (5,5), (5,5,2)x(5,5)**

In [82]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below

# reshape matrix B so they have compatible dimensions
result_matrix = A*B.reshape(5,5,1)

print(result_matrix.shape)

(5, 5, 3)


### **21. Swap the first and second rows of the 2D array below**

In [83]:
W = np.arange(30).reshape(6,5)
print("Array W:")
print(W)
print()
# Include your solution below

#Swapping the first and second rows
W[[0,1]] = W[[1,0]]
print("Array W (with first and second rows swapped:)")
print(W)

Array W:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Array W (with first and second rows swapped:)
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### **22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box that encloses all non-zero elements in the input array**

In [84]:
def bbox(img):
    #include your solution below
    r,c = np.where(img != 0)
    #r1 & c1 are minmum points
    #r2 & c2 are maximum points
    r1 = min(r)
    c1 = min(c)
    r2 = max(r)
    c2 = max(c)
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


### **23.Write a function to compute the average over a sliding window of length N over a 1D array?**

In [85]:
def moving_average(x,N = 3):
    #define your function here
    x_range = int(len(x)/N)
    x = np.reshape(x,(x_range,N))
    x_avg = np.mean(x, axis=1)
    return x_avg

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


### **24. Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

In [86]:
C = np.bincount([1,1,2,3,4,4,6])
print(f"bincount: {C}")
# Include yoru solution here

# First use the default arange function to get the range of the array (starting from 0)
range_array = np.arange(len (C))
print(f"range array: {range_array}")

# Then use the default repeat function to repeat the numbers inside array r for C times
converted_array = np.repeat(range_array, C)
print(f"converted_array: {converted_array}")


bincount: [0 2 1 1 2 0 1]
range array: [0 1 2 3 4 5 6]
converted_array: [1 1 2 3 4 4 6]


### **25. Find the most frequent value in the array below?**

In [87]:
Z = np.random.randint(0,10,50)
# Include your solution below

print("Print the randomized array: ",Z)
bincount_array = np.bincount(Z)
print("Print the bincount of the array: ", bincount_array)
# Normally we can use argmax：Returns the indices of the maximum values 
# But argmax does not consider the case of multiple max values, so we took a different approach

# get the maximum amount of time a value appears
highest_frequency = np.max(bincount_array)
print(f"The most frequent value(s) in the array appear {highest_frequency} times")
#select the indexes of the bincount array where the frequency is equal to the highest frequency
most_frequent_values = np.where(bincount_array == highest_frequency)[0]
print(f"The most frequent value(s) are: {most_frequent_values}")

Print the randomized array:  [4 8 6 2 1 0 7 8 0 4 0 8 5 0 4 4 3 3 1 6 5 5 6 5 7 6 3 4 5 0 3 1 3 6 5 9 9
 0 2 4 3 6 8 7 1 5 1 8 4 2]
Print the bincount of the array:  [6 5 3 6 7 7 6 3 5 2]
The most frequent value(s) in the array appear 7 times
The most frequent value(s) are: [4 5]


### **26. Write a function to return the n largest values of an array**

In [88]:
def nlargest(a,n = 5):
    # Include your solution here
    indexes = np.argsort(a)
    sorted_array = a[indexes]
    largest_values = sorted_array[-n :]
    return largest_values

def nlargestIndex(a,n = 5):
    #argsort returns an array of indices of the same shape as a that index data along the given axis in sorted order
    indexes = np.argsort(a)
    highest_values_indexes = indexes[-n :]
    return highest_values_indexes

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Since Z is from number 0-9999, then the highest values are always going to be 999ish
# We've also included the function that get the largest values index below
print("Largest ", n, "values are:", nlargest(Z,n))    
print("Largest ", n, "values' index are:",nlargestIndex(Z,n))    

Largest  5 values are: [9995 9996 9997 9998 9999]
Largest  5 values' index are: [4503 2520 2803 3830 5913]
